
package com.ewell.upload.webservice.FYClientPro;

import org.springframework.stereotype.Component;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Mchis", targetNamespace = "http://webservice.zhending.com", wsdlLocation = "http://10.75.93.91:8080/mchis-controller/services/Mchis?wsdl")
@Component
public class Mchis
    extends Service
{

    private final static URL MCHIS_WSDL_LOCATION;
    private final static WebServiceException MCHIS_EXCEPTION;
    private final static QName MCHIS_QNAME = new QName("http://webservice.zhending.com", "Mchis");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.75.93.91:8080/mchis-controller/services/Mchis?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MCHIS_WSDL_LOCATION = url;
        MCHIS_EXCEPTION = e;
    }

    public Mchis() {
        super(__getWsdlLocation(), MCHIS_QNAME);
    }

    public Mchis(WebServiceFeature... features) {
        super(__getWsdlLocation(), MCHIS_QNAME, features);
    }

    public Mchis(URL wsdlLocation) {
        super(wsdlLocation, MCHIS_QNAME);
    }

    public Mchis(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MCHIS_QNAME, features);
    }

    public Mchis(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Mchis(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MchisPortType
     */
    @WebEndpoint(name = "MchisHttpSoap11Endpoint")
    public MchisPortType getMchisHttpSoap11Endpoint() {
        return super.getPort(new QName("http://webservice.zhending.com", "MchisHttpSoap11Endpoint"), MchisPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MchisPortType
     */
    @WebEndpoint(name = "MchisHttpSoap11Endpoint")
    public MchisPortType getMchisHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.zhending.com", "MchisHttpSoap11Endpoint"), MchisPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MCHIS_EXCEPTION!= null) {
            throw MCHIS_EXCEPTION;
        }
        return MCHIS_WSDL_LOCATION;
    }

}
