
package com.ewell.upload.webservice.client;

import java.util.List;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MchisPortType", targetNamespace = "http://webservice.zhending.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MchisPortType {


    /**
     * 
     * @param json
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:deleteData")
    @WebResult(targetNamespace = "http://webservice.zhending.com")
    @RequestWrapper(localName = "deleteData", targetNamespace = "http://webservice.zhending.com", className = "com.ewell.upload.webservice.client.DeleteData")
    @ResponseWrapper(localName = "deleteDataResponse", targetNamespace = "http://webservice.zhending.com", className = "com.ewell.upload.webservice.client.DeleteDataResponse")
    public String deleteData(
        @WebParam(name = "token", targetNamespace = "http://webservice.zhending.com")
        String token,
        @WebParam(name = "json", targetNamespace = "http://webservice.zhending.com")
        String json);

    /**
     * 
     * @param json
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:saveData")
    @WebResult(targetNamespace = "http://webservice.zhending.com")
    @RequestWrapper(localName = "saveData", targetNamespace = "http://webservice.zhending.com", className = "com.ewell.upload.webservice.client.SaveData")
    @ResponseWrapper(localName = "saveDataResponse", targetNamespace = "http://webservice.zhending.com", className = "com.ewell.upload.webservice.client.SaveDataResponse")
    public String saveData(
        @WebParam(name = "token", targetNamespace = "http://webservice.zhending.com")
        String token,
        @WebParam(name = "json", targetNamespace = "http://webservice.zhending.com")
        String json);

    /**
     * 
     * @param password
     * @param loginCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:login")
    @WebResult(targetNamespace = "http://webservice.zhending.com")
    @RequestWrapper(localName = "login", targetNamespace = "http://webservice.zhending.com", className = "com.ewell.upload.webservice.client.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://webservice.zhending.com", className = "com.ewell.upload.webservice.client.LoginResponse")
    public String login(
        @WebParam(name = "loginCode", targetNamespace = "http://webservice.zhending.com")
        String loginCode,
        @WebParam(name = "password", targetNamespace = "http://webservice.zhending.com")
        String password);

    /**
     * 
     * @param json
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:getData")
    @WebResult(targetNamespace = "http://webservice.zhending.com")
    @RequestWrapper(localName = "getData", targetNamespace = "http://webservice.zhending.com", className = "com.ewell.upload.webservice.client.GetData")
    @ResponseWrapper(localName = "getDataResponse", targetNamespace = "http://webservice.zhending.com", className = "com.ewell.upload.webservice.client.GetDataResponse")
    public String getData(
        @WebParam(name = "token", targetNamespace = "http://webservice.zhending.com")
        String token,
        @WebParam(name = "json", targetNamespace = "http://webservice.zhending.com")
        String json);

    /**
     * 
     * @param keyChilds
     * @param keys
     * @param redisCacheManager
     */
    @WebMethod(action = "urn:addCaches")
    @Oneway
    @RequestWrapper(localName = "addCaches", targetNamespace = "http://webservice.zhending.com", className = "com.ewell.upload.webservice.client.AddCaches")
    public void addCaches(
        @WebParam(name = "redisCacheManager", targetNamespace = "http://webservice.zhending.com")
        RedisCacheManager redisCacheManager,
        @WebParam(name = "keys", targetNamespace = "http://webservice.zhending.com")
        List<String> keys,
        @WebParam(name = "keyChilds", targetNamespace = "http://webservice.zhending.com")
        String keyChilds);

}
